### ISSUE TITLE
WMS error 400 for Sentinel 3 OLCI and for some products of Sentinel-1 and Sentinel-2

### ISSUE THREAD

**Issue by achtsnits** [eurodatacube/ogc-edc#1]
When selecting several display options, we did not get results in the viewport. While examining the console network, we noticed that we received a WMS error 400. This happened for all the Sentinel-3 OLCI visualizations, as well as the last four products of Sentinel-1 and two products of S2L1C (NDVI and moisture index).

**Comment by constantinius** [comment]
Sentinel-3 should now work, as well as S2L1C layers

Sentinel-1 is only regionally available, this cannot be handled in the OGC layer gracefully
