### ISSUE TITLE
error 400 - dim_bands empty

### ISSUE THREAD

**Issue by achtsnits** [eurodatacube/ogc-edc#2]
With S2L2A custom band selection, we got an error 400 as well. It seems as if the app didn’t input the chosen bands into the WMS request, since “dim_bands” stayed empty. When we input the bands into the URL by hand, the request worked.

**Comment by lubojr** [comment]
Is fixed with newest eoxc bundle. Inserting values into request works as expected.

**Comment by achtsnits** [comment]
fixing version of EOxC bundled with ogc-edc >= 0.10.0
