### ISSUE TITLE
WCS download problems - error linear is not support

### ISSUE THREAD

**Issue by achtsnits** [eurodatacube/ogc-edc#3]
We couldn’t get downloads to work; we only either got a black result, or a result, that didn’t match the viewport image. If we chose an interpolation method, such as bilinear interpolation, we got a “'linear' is not supported” error

**Comment by lubojr** [comment]
Should be now fixed in newest eoxc bundle. Client offers two interpolations: bilinear and bicubic and both seem to be applied.

**Comment by achtsnits** [comment]
fixing version of EOxC bundled with ogc-edc >= 0.10.0
