### ISSUE TITLE
Layer name not shown in QGIS

### ISSUE THREAD

**Issue by achtsnits** [eurodatacube/ogc-edc#4]
We could not make the given ULR work in QGIS. The layers did list in the Browser and Layers windows, but no layer names were displayed. The layers didn’t draw in the viewport window even after zooming all the way in or clicking the “zoom to layer” option.
 
![issue](https://user-images.githubusercontent.com/54577319/68596952-65599380-049c-11ea-96e8-f2cf23f132a2.png)

**Comment by constantinius** [comment]
Fixed with 94e9a054e5fc7f0ddb8a52eb7ecf3e79de2057c3 793e1adacc6223018d6c72c7314ba134ffb55c30 d8bdb18ccb69dc79139c10e5f22319e93bb1a2c7

**Comment by achtsnits** [comment]
available with (already published) version 0.11.0
