### ISSUE TITLE
Deploying new OGC service does not work

### ISSUE THREAD

**Issue by gmilcinski** [eurodatacube/ogc-edc#6]
I tried to deploy new OGC instance using marketplace but the wheel keep on turning....   
It seems it tried to do one here:  
https://o33as4x49fw40n9.ae8d1432-MASKED.hub.eox.at/

**Comment by Schpidi** [comment]
The deploy button shouldn't have been activated as the prerequisites hadn't been met (SH subscription) cc @silvester-pari
