### ISSUE TITLE
Adjust WCS widget limitations

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/ogc-edc#7]
Currently there is only a check for the spatial subset to not exceed a configured limit. We should also add a check for resolution as any request with pixelsize >250m fails, even if only a handful pixels are requested (https://docs.sentinel-hub.com/api/latest/#/data/Sentinel-2-L1C?id=previewmode).

**Comment by lubojr** [comment]
Implemented in 317af81b3feaca41b4795f9d66d4396622b1a23f
