### ISSUE TITLE
Check that all advertised layers actually work

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/ogc-edc#9]
For example loading them in QGIS currently yields a number of issues:

- `an error occured: Internal Server Error, status code 500: b'{"error":{"status":500,"reason":"Internal Server Error","message":"java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Band not in current Sentinel 1 image source.","code":"RENDERER_EXCEPTION"}}'`
- `an error occured: Bad Request, status code 400: b'{"error":{"status":400,"reason":"Bad Request","message":"Failed to evaluate script!\\nevalscript.js:4: SyntaxError: Illegal return statement\\nreturn colorBlend(index, [-0.8, -0.24, -0.032, 0.032, 0.24, 0.8], [[0.5,0,0], [1,0,0], [1,1,0], [0,1,1], [0,0,1], [0,0,0.5]]);\\n^^^^^^\\n","code":"RENDERER_EXCEPTION"}}'`
- `an error occured: Service Unavailable, status code 503: b'
503 Service Unavailable
\nNo server is available to handle this request.\n\n\n'`

**Comment by constantinius** [comment]
Various problems have been fixed related to this issue:

- automatic translation to V3 scripts
- using appropriate MDI endpoints for some datasets
- several small fixes

I'll close this now, please reopen if it reoccurs
